export const samples = {
	"State Machine": "digraph finite_state_machine {\n\trankdir=LR;\n\tsize=\"8,5\"\n\tnode [shape = doublecircle]; LR_0 LR_3 LR_4 LR_8;\n\tnode [shape = circle];\n\tLR_0 -> LR_2 [ label = \"SS(B)\" ];\n\tLR_0 -> LR_1 [ label = \"SS(S)\" ];\n\tLR_1 -> LR_3 [ label = \"S($end)\" ];\n\tLR_2 -> LR_6 [ label = \"SS(b)\" ];\n\tLR_2 -> LR_5 [ label = \"SS(a)\" ];\n\tLR_2 -> LR_4 [ label = \"S(A)\" ];\n\tLR_5 -> LR_7 [ label = \"S(b)\" ];\n\tLR_5 -> LR_5 [ label = \"S(a)\" ];\n\tLR_6 -> LR_6 [ label = \"S(b)\" ];\n\tLR_6 -> LR_5 [ label = \"S(a)\" ];\n\tLR_7 -> LR_8 [ label = \"S(b)\" ];\n\tLR_7 -> LR_5 [ label = \"S(a)\" ];\n\tLR_8 -> LR_6 [ label = \"S(b)\" ];\n\tLR_8 -> LR_5 [ label = \"S(a)\" ];\n}\n",
	"Clustering": "# http://www.graphviz.org/content/cluster\ndigraph G {\n\n\tsubgraph cluster_0 {\n\t\tstyle=filled;\n\t\tcolor=lightgrey;\n\t\tnode [style=filled,color=white];\n\t\ta0 -> a1 -> a2 -> a3;\n\t\tlabel = \"process #1\";\n\t}\n\n\tsubgraph cluster_1 {\n\t\tnode [style=filled];\n\t\tb0 -> b1 -> b2 -> b3;\n\t\tlabel = \"process #2\";\n\t\tcolor=blue\n\t}\n\n\tstart -> a0;\n\tstart -> b0;\n\ta1 -> b3;\n\tb2 -> a3;\n\ta3 -> a0;\n\ta3 -> end;\n\tb3 -> end;\n\n\tstart [shape=Mdiamond];\n\tend [shape=Msquare];\n}\n",
	"Clustering 2": "# Taken from:\n# https://hbfs.wordpress.com/2014/09/30/a-quick-primer-on-graphviz/\n\ngraph g {\n\tlayout=fdp # Specify used layout engine\n\n\tbgcolor=\"#ffffff00\"\n\toverlap=scale\n\n\tstart=2\n\tedge [penwidth=0.75,arrowsize=0.6]\n\tedge [color=black, fontsize=8, forcelabels=true]\n\n\tnode [\n\t\t\tshape=circle,\n\t\t\tfixedsize=true,\n\t\t\twidth=0.25,\n\t\t\tcolor=\"black\",\n\t\t\tfillcolor=\"white\",\n\t\t\tstyle=\"filled,solid\",\n\t\t\tfontsize=12,\n\t\t];\n\n\tnode1 [label=\"s₁\"] # u+2081 (yes, it can do unicode!)\n\tnode2 [label=\"s₂\"]\n\tnode3 [label=\"s₃\"]\n\tnode4 [label=\"t₁\",pos=\"0,0\"]\n\tnode5 [label=\"t₂\",pos=\"0,1\"]\n\tnode6 [label=\"t₃\",pos=\"1,1\"]\n\tnode7 [label=\"t₄\",pos=\"1,0\"]\n\n\tsubgraph clusterG0 {\n\t\tlabel=\"G∪T\" # union u+222a\n\n\n\t\tsubgraph clusterG1 {\n\t\t\t\tlabel=\"G\"\n\t\t\t\tbgcolor=white\n\t\t\t\tnode1 -- node2\n\t\t\t\tnode2 -- node3\n\t\t\t\tnode3 -- node1\n\t\t}\n\n\t\tnode3 -- node6 [style=dashed,penwidth=1]\n\n\t\tsubgraph clusterG2 {\n\t\t\t\tlabel=\"H\"\n\t\t\t\tbgcolor=white\n\t\t\t\tnode4 -- node5\n\t\t\t\tnode5 -- node6\n\t\t\t\tnode6 -- node4\n\t\t\t\tnode6 -- node7\n\t\t}\n\t}\n}",
	"Huffman Tree": "/* \n\tHuffman Tree DOT graph.\n\tPhrase: 'EDOTOR IS AWESOME'\n\tGenerated on http://huffman.ooz.ie/\n*/\n\ndigraph G {\n\tedge [label=0];\n\tgraph [ranksep=0];\n\tO [shape=record, label=\"{{O|3}|00}\"];\n\tSPACE [shape=record, label=\"{{SPACE|2}|010}\"];\n\tS [shape=record, label=\"{{S|2}|011}\"];\n\tI [shape=record, label=\"{{I|1}|1000}\"];\n\tM [shape=record, label=\"{{M|1}|1001}\"];\n\tA [shape=record, label=\"{{A|1}|1010}\"];\n\tD [shape=record, label=\"{{D|1}|1011}\"];\n\tAD [label=2];\n\tIMAD [label=4];\n\tW [shape=record, label=\"{{W|1}|1100}\"];\n\tR [shape=record, label=\"{{R|1}|11010}\"];\n\tT [shape=record, label=\"{{T|1}|11011}\"];\n\tRT [label=2];\n\tE [shape=record, label=\"{{E|3}|111}\"];\n\t17 -> 7 -> O;\n\t4 -> SPACE;\n\t10 -> IMAD -> 2 -> I;\n\tAD -> A;\n\t6 -> 3 -> W;\n\tRT -> R;\n\t7 -> 4 -> S [label=1];\n\t2 -> M [label=1];\n\tIMAD -> AD -> D [label=1];\n\t3 -> RT -> T [label=1];\n\t17 -> 10 -> 6 -> E [label=1];\n}\n",
	"Hamming Distance": "# Taken from:\n# https://hbfs.wordpress.com/2014/09/30/a-quick-primer-on-graphviz/\n\n# Try engine \"neato\"\n\ngraph g {\n\tratio=fill\n\tsplines=spline\n\toverlap=scale\n\n\tnode [\n\t\t\tshape=circle,\n\t\t\tfixedsize=true,\n\t\t\twidth=0.3,\n\t\t\tcolor=\"black\",\n\t\t\tfillcolor=\"#eeeeee\",\n\t\t\tstyle=\"filled,solid\",\n\t\t\tfontsize=12\n\t\t]\n\n\tq0 [label=\"0\", xlabel=\"000\", pos=\"0,0\"]\n\tq1 [label=\"1\", xlabel=\"001\", pos=\"0,1\"]\n\tq2 [label=\"2\", xlabel=\"010\", pos=\"1,0\"]\n\tq3 [label=\"3\", xlabel=\"011\", pos=\"1,1\"]\n\n\tq4 [label=\"4\", xlabel=\"100\", pos=\"-0.5,-0.5\"]\n\tq5 [label=\"5\", xlabel=\"101\", pos=\"-0.5,0.5\"]\n\tq6 [label=\"6\", xlabel=\"110\", pos=\"0.5,-0.5\"]\n\tq7 [label=\"7\", xlabel=\"111\", pos=\"0.5,0.5\"]\n\n\tq0 -- q1\n\tq0 -- q2\n\tq1 -- q3\n\tq2 -- q3\n\n\tq4 -- q5\n\tq4 -- q6\n\tq5 -- q7\n\tq6 -- q7\n\n\tq0 -- q4\n\tq1 -- q5\n\tq2 -- q6\n\tq3 -- q7\n}\n",
	"Attribute Demo": "graph graphname {\n\t// This attribute applies to the graph itself\n\tsize=\"1,1\";\n\t// The label attribute can be used to change the label of a node\n\ta [label=\"Foo\"];\n\t// Here, the node shape is changed.\n\tb [shape=box];\n\t// These edges both have different line properties\n\ta -- b -- c [color=blue];\n\tb -- d [style=dotted];\n\t// [style=invis] hides a node.\n}\n",
	"Contact": "digraph {\n\trankdir=LR;\n\thello -> edotor [label=\"@\"]\n\tedotor -> net [label=\".\"]\n}\n",
	"Empty Graph": "digraph {\n}\n",
};
